# Generated by Django 4.0.5 on 2022-06-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minTime', models.FloatField()),
                ('maxTime', models.FloatField()),
                ('meanTime', models.FloatField()),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=40)),
                ('time', models.FloatField()),
                ('method', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=15)),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.metrics')),
            ],
        ),
    ]
