# Generated by Django 4.0.5 on 2022-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_metrics_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='counter',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='maxTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='meanTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='minTime',
            field=models.FloatField(null=True),
        ),
    ]
