# Generated by Django 4.0.5 on 2022-06-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0004_request_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=40)),
                ('method', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='metrics',
        ),
    ]
